#+BEGIN_COMMENT
.. title: Choosing a blogging tool
.. slug: choosing-a-blogging-tool
.. date: 2016-08-18 12:17:14 UTC-07:00
.. tags: 
.. category: Blogospheric navel gazing 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

So, once one has decided to cast one's words out to the merciless seas of
    information a.k.a. The Internet, how to go about it?
    
    The easiest solution is of course using one of the many pre-packaged blog
    sites (Blogger, Wordpress, etc). This is a perfectly valid way to do it,
    especially if one is not technically inclined. But, you know, boring if one is.

    I want to keep things as simple as possible, make sure I own my data, have
    total freedom to play with templates and themes, and have flexibility with
    how to write for the site. I don't want to deal with the headaches
    associated with running a database backed site like Wordpress either.

    The best thing is a static site generator. The idea has been around forever,
    it's how it all worked on the early internet (well, except all the HTML was
    hand crafted, or you used some terrible "HTML editor"). There are dozens
    of the modern static site generators around, from Jekyll which made it
    popular, to he new hotness on the block, Hugo. I chose to go with neither of
    those. Instead I chose [[http://getnikola.com][Nikola]].

**** Why Nikola
     [[http://getnikola.com][Nikola]] has been around for a while. It may not be as popular as some of the
     other comparable tools, but it is certainly one of the most flexible. It
     supports most markup languages out of the box: Markdown, Restructured Text,
     Asciidoc, even Emacs Orgmode as well as hand-written HTML. The competition
     tends to be mostly just Markdown.

     It is written in Python, which I understand better than Ruby or Go. It
     seems to be the most active of the Python-based systems today. I haven't
     delved into the source, but it appears altogether well thought out.

     The only downside with Nikola, and most likely the reason it is not as
     popular as it could be, is that its theme selection is rather limited and
     frankly not very pretty. Since I've taken an interest in front-end web dev
     lately (just for fun for now), I'm hoping I can contribute a theme or two. So
     for me personally this downside is an opportunity.

**** Why Github Pages
     For a tech-focused blog, publishing for free on [[https://pages.github.com][Github Pages]] (github.io) is
     a no-brainer. With a static blog engine, you get the freedom to work on
     your posts anywhere, even offline. And with Github, you of course have your
     precious writing under version control. Backups are never more than a
     simple -git clone- / -git pull-. And should I decide to move elsewhere, I can
     just -git push- to an AWS [[http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html][S3 backed static blog]], for example.

     Nikola has support for Github Pages, -nikola github_deploy- does all the
     magic, putting the source files in one git branch, and the rendered HTML
     into the master branch. 

**** Here today
     This is where I'm today. If Nikola turns out to be more pain than it's
     worth, I can easily switch to another site generator. I own my own data,
     it's in plain text, the data format of kings and unix beards. The software
     is free and Free. Isn't modern life pretty damn wonderful?
